# Generated by Django 4.2 on 2023-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=200, verbose_name='aluno')),
                ('professor', models.CharField(choices=[('João Neto - Álgebra Linear', 'João Neto - Álgebra Linear'), ('Orlando Júnior - Desenvolvimento Web III', 'Orlando Júnior - Desenvolvimento Web III'), ('Nilton Sacco - Banco de Dados Relacional', 'Nilton Sacco - Banco de Dados Relacional'), ('Esdras da Silva - Técnicas de Programação II', 'Esdras da Silva - Técnicas de Programação II')], max_length=200, verbose_name='professor')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
