# Generated by Django 4.2 on 2023-06-13 00:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('aluno', models.CharField(max_length=200, validators=[core.models.validate_min_length], verbose_name='aluno')),
                ('professor', models.CharField(choices=[('João Neto', 'João Neto'), ('Orlando Júnior', 'Orlando Júnior'), ('Nilton Sacco', 'Nilton Sacco'), ('Esdras da Silva', 'Esdras da Silva')], max_length=200, verbose_name='professor')),
                ('materia', models.CharField(choices=[('Álgebra Linear', 'Álgebra Linear'), ('Desenvolvimento Web III', 'Desenvolvimento Web III'), ('Banco de Dados Relacional', 'Banco de Dados Relacional'), ('Técnicas de Programação II', 'Técnicas de Programação II')], max_length=200, verbose_name='materia')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
